global:
  scrape_interval:     15s # By default, scrape targets every 15 seconds.
  evaluation_interval: 15s # Evaluate rules every 15 seconds.

scrape_configs:
  - job_name: db
    scrape_interval: 10s
    static_configs:
      - targets: ['query-exporter:9560']
